2021/12/16 19:19:03 [emerg] 1#1: host not found in upstream "filerun" in /etc/nginx/nginx.conf:71
2021/12/16 19:19:04 [emerg] 1#1: host not found in upstream "filerun" in /etc/nginx/nginx.conf:71
2021/12/16 19:19:05 [emerg] 1#1: host not found in upstream "filerun" in /etc/nginx/nginx.conf:71
2021/12/16 19:19:06 [emerg] 1#1: host not found in upstream "filerun" in /etc/nginx/nginx.conf:71
2021/12/16 19:19:07 [emerg] 1#1: host not found in upstream "filerun" in /etc/nginx/nginx.conf:71
2021/12/16 19:19:09 [emerg] 1#1: host not found in upstream "filerun" in /etc/nginx/nginx.conf:71
2021/12/16 19:19:13 [emerg] 1#1: host not found in upstream "filerun" in /etc/nginx/nginx.conf:71
2021/12/16 19:19:20 [emerg] 1#1: host not found in upstream "filerun" in /etc/nginx/nginx.conf:71
2021/12/16 19:19:33 [emerg] 1#1: host not found in upstream "filerun" in /etc/nginx/nginx.conf:71
2021/12/16 19:19:59 [emerg] 1#1: host not found in upstream "filerun" in /etc/nginx/nginx.conf:71
2021/12/16 19:20:51 [emerg] 1#1: host not found in upstream "filerun" in /etc/nginx/nginx.conf:71
2021/12/16 19:21:23 [error] 32#32: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: localhost, request: "POST /api/auth/login HTTP/1.1", upstream: "http://172.20.0.2:8529/_db/cenoteando/api/auth/login", host: "localhost", referrer: "http://localhost/login"
